version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_raw_tables.sql:/docker-entrypoint-initdb.d/init_raw_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  webserver:
    build:
      context: .
      dockerfile: DockerFile
    image: airflow-with-dbt
    container_name: airflow_webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: -xcLLUBgCB7fcy2zUN-Ix1xwcXk4Z5xouLI-HjJVmUg
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ../dbt_project:/opt/airflow/dbt_project
      - ../.dbt:/home/airflow/.dbt
      - ./dags:/opt/airflow/dags
      - ../data:/opt/airflow/data
      - ./profiles.yml:/home/airflow/.dbt/profiles.yml
    ports:
      - "8080:8080"
      - "8081:8081"
    command: bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && airflow webserver"

  scheduler:
    build:
      context: .
      dockerfile: DockerFile
    image: airflow-with-dbt
    container_name: airflow_scheduler
    restart: always
    depends_on:
      webserver:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: -xcLLUBgCB7fcy2zUN-Ix1xwcXk4Z5xouLI-HjJVmUg
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ../dbt_project:/opt/airflow/dbt_project
      - ../.dbt:/home/airflow/.dbt
      - ./dags:/opt/airflow/dags
      - ../data:/opt/airflow/data
      - ./profiles.yml:/home/airflow/.dbt/profiles.yml
    command: bash -c "airflow scheduler"

volumes:
  postgres_data:
