ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'postgres') }}"
      user: airflow
      password: airflow
      port: 5432
      dbname: ecommerce
      schema: analytics
      threads: 4
