ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal # ← use localhost if you didn't change the Docker port
      user: dbt_user
      password: dbt_pass
      port: 5433 # ← use 5432 if you didn't change the Docker port
      dbname: ecommerce
      schema: analytics
      threads: 4
