name: CI - dbt Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U airflow"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          ecommerce_dbt:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                port: 5433
                user: airflow
                password: airflow
                dbname: airflow
                schema: public
                threads: 4
          EOF

      - name: Run dbt deps
        run: dbt deps --project-dir dbt_project/ecommerce_dbt

      - name: Run dbt build
        run: dbt build --project-dir dbt_project/ecommerce_dbt --profiles-dir ~/.dbt
