name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5433 -U airflow; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Load raw tables with init_db.sql
        run: |
          PGPASSWORD=airflow psql -h localhost -p 5433 -U airflow -d airflow -f init_db.sql

      - name: Run dbt deps
        working-directory: ./dbt_project/ecommerce_dbt
        run: dbt deps --profiles-dir .dbt

      - name: Run dbt build
        working-directory: ./dbt_project/ecommerce_dbt
        run: dbt build --profiles-dir .dbt
