name: dbt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: dbt_user
          POSTGRES_PASSWORD: dbt_pass
          POSTGRES_DB: ecommerce
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-core and adapter
        run: |
          pip install dbt-core dbt-postgres

      - name: Create CI profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          ecommerce_dbt:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                user: dbt_user
                password: dbt_pass
                port: 5433
                dbname: ecommerce
                schema: analytics
                threads: 4
          EOL

      - name: Run dbt build
        working-directory: ./dbt_project/ecommerce_dbt
        run: dbt build --profiles-dir ~/.dbt
